### ISSUE TITLE
Automatic `lockFiles` detection?

### ISSUE THREAD

**Issue by kolpav** [mdarocha/nuget-packageslock2nix#1]
First of all, thank you for this project. Building .NET in Nix finally resembles something I would like to use, and your project might be the last piece I need.

I am still trying to make this work, but do you think it would be possible to not have to explicitly state package.lock.json locations, so it's even easier to set up and get going?

It would also be great if you could somehow make this project part of any of the many Nix docs. The .NET community is huge, and being able to build your solution with just a few lines of Nix code might be something that brings some of the .NET developers over to the Nix side. I gave up a few months back due to the fiddling with NuGet dependencies and Nix generation.

It might also be worth mentioning https://devblogs.microsoft.com/nuget/introducing-central-package-management somewhere in the README so people have bit easier time managing their deps versions.

Lastly is any of the new build options https://learn.microsoft.com/en-us/dotnet/core/deploying more preferable than others when building?

**Comment by kolpav** [comment]
This is what copilot spit up

```nix
lockFiles = builtins.filter (path: builtins.hasSuffix ".lock.json" path) (builtins.attrNames (builtins.readDir ./api/BidClick));
```

lets see if it works...

**Comment by kolpav** [comment]
With help of both copilot and chatgpt I came up with
```nix
builtins.filterSource (path: type: type == "regular" && baseNameOf path == "packages.lock.json") ./.
```
gpt-4 and I will be able to write nix

**Comment by mdarocha** [comment]
Hey, nice to see you found this useful!

> I am still trying to make this work, but do you think it would be possible to not have to explicitly state package.lock.json locations, so it's even easier to set up and get going?

Yeah, I had some problems with finding those lockfiles automatically, but if you figure it out, PRs welcome :)

> It would also be great if you could somehow make this project part of any of the many Nix docs. The .NET community is huge, and being able to build your solution with just a few lines of Nix code might be something that brings some of the .NET developers over to the Nix side. I gave up a few months back due to the fiddling with NuGet dependencies and Nix generation.

This repo is pretty experimental, so I designed it as a flake drop-in. I don't think including this in nixpkgs will be useful, since none of the packages in nixpkgs that use `buildDotnetModules` have package locks commited. It's more useful for end-users building their private projects with Nix, so I believe its best left as a separate flake or included in a larger project like dream2nix.

> It might also be worth mentioning https://devblogs.microsoft.com/nuget/introducing-central-package-management somewhere in the README so people have bit easier time managing their deps versions.

This is pretty useful, but not necessary for this to work and therefore unrelated.

> Lastly is any of the new build options https://learn.microsoft.com/en-us/dotnet/core/deploying more preferable than others when building?

There's no much difference. When deploying to non-Nix platforms (ie. a Windows binary), a self-deployed build is preferable, so that you don't have to manage system depedencies.

On Nix, framework-dependant build is preffered, since dependencies are no problem, and you can potentially benefit from deduplication of .NET binaries in /nix/store, if multiple .NET apps are installed in the system.

**Comment by kolpav** [comment]
Good points I'll check the dream2nix it seems like it would be great fit even more so with automatic lockfiles discovery. Thank you for answer I'll close this for now and give PR a try in the future if I manage to make it work.
